branches:
  only:
    - master
    - dev

notifications:
  irc:
    channels:
      - "chat.freenode.net#solarus"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libluajit-5.1-dev
    - libphysfs-dev
    - libopenal-dev
    - libmodplug-dev
    - libvorbis-dev
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make && ctest -V

