branches:
  only:
    - master

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # gcc 4.8
  - sudo apt-add-repository -y ppa:kalakris/cmake          # cmake >= 2.8.11
  - sudo apt-add-repository -y ppa:zoogie/sdl2-snapshots   # SDL2
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo apt-get install -y cmake libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libluajit-5.1-dev libphysfs-dev libopenal-dev libmodplug-dev libvorbis-dev

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make && make test

