branches:
  only:
    - master
    - dev

notifications:
  irc:
    channels:
      - "chat.freenode.net#solarus"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
        #    - libsdl2-dev
    # - libsdl2-image-dev
    # - libsdl2-ttf-dev
    - libluajit-5.1-dev
    - libphysfs-dev
    - libopenal-dev
    - libmodplug-dev
    - libvorbis-dev
    - libglm-dev
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools

before_script:
    # install SDL
  - wget -q http://www.libsdl.org/release/SDL2-2.0.4.tar.gz
  - tar xf SDL2-*.tar.gz
  - cd SDL2-* && ./configure && make && sudo make install && cd ..

  # Install SDL_ttf.
  - wget -q http://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.12.tar.gz
  - tar xf SDL2_ttf-*.tar.gz
  - cd SDL2_ttf-* && ./configure && make && sudo make install && cd ..

  - wget -q https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.3.tar.gz
  - tar xf SDL2_image*
  - cd SDL2_image* && ./configure && make && sudo make install && cd ..

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make && ctest -V

